# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ejs-rcompiler}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ben Curren"]
  s.date = %q{2010-09-27}
  s.description = %q{ejs to js ruby compiler}
  s.email = %q{ben@outright.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "autotest/discover.rb",
     "ejs-rcompiler.gemspec",
     "lib/ejs-rcompiler.rb",
     "lib/ejs/compiler.rb",
     "lib/ejs/grammar.rb",
     "lib/ejs/grammar.treetop",
     "lib/ejs/parse_error.rb",
     "lib/ejs/parser.rb",
     "spec/compiler_spec.rb",
     "spec/fixtures/or.ui.Cities.ejs",
     "spec/fixtures/or.ui.Cities.js",
     "spec/parser_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/bcurren/ejs-rcompiler}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{TODO: one-line summary of your gem}
  s.test_files = [
    "spec/compiler_spec.rb",
     "spec/parser_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<treetop>, [">= 1.4.0"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<treetop>, [">= 1.4.0"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<treetop>, [">= 1.4.0"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

