# Autogenerated from a Treetop grammar. Edits may be lost.


module Ejs
  module Grammar
    include Treetop::Runtime

    def root
      @root ||= :program
    end

    module Program0
      def compile(template_name)
        build(template_name).join('\n')
      end
      
      def compile(template_name, array = false)
        results = []
        
        # Append function header
        results.push <<-EOF
          #{template_name}.template = function(options) {
            var p = [];
            with(options) { 
        EOF
        
        # Append function body
        elements.each do |element|
          value = element.compile
          results.push(value) if value
        end
        
        # Append function footer
        results.push <<-EOF
            }
            return out.join('');
          }
        EOF
        
        array ? results : results.join("\n")
      end
    end

    def _nt_program
      start_index = index
      if node_cache[:program].has_key?(index)
        cached = node_cache[:program][index]
        if cached
          cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
          @index = cached.interval.end
        end
        return cached
      end

      s0, i0 = [], index
      loop do
        r1 = _nt_content
        if r1
          s0 << r1
        else
          break
        end
      end
      r0 = instantiate_node(SyntaxNode,input, i0...index, s0)
      r0.extend(Program0)

      node_cache[:program][start_index] = r0

      r0
    end

    def _nt_content
      start_index = index
      if node_cache[:content].has_key?(index)
        cached = node_cache[:content][index]
        if cached
          cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
          @index = cached.interval.end
        end
        return cached
      end

      i0 = index
      r1 = _nt_output_content
      if r1
        r0 = r1
      else
        r2 = _nt_comment
        if r2
          r0 = r2
        else
          r3 = _nt_execute_content
          if r3
            r0 = r3
          else
            r4 = _nt_static_content
            if r4
              r0 = r4
            else
              @index = i0
              r0 = nil
            end
          end
        end
      end

      node_cache[:content][start_index] = r0

      r0
    end

    module StaticContent0
    end

    module StaticContent1
      def compile
        "p.push('#{text_value}');"
      end
    end

    def _nt_static_content
      start_index = index
      if node_cache[:static_content].has_key?(index)
        cached = node_cache[:static_content][index]
        if cached
          cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
          @index = cached.interval.end
        end
        return cached
      end

      s0, i0 = [], index
      loop do
        i1, s1 = index, []
        i2 = index
        if has_terminal?('<%', false, index)
          r3 = instantiate_node(SyntaxNode,input, index...(index + 2))
          @index += 2
        else
          terminal_parse_failure('<%')
          r3 = nil
        end
        if r3
          r2 = nil
        else
          @index = i2
          r2 = instantiate_node(SyntaxNode,input, index...index)
        end
        s1 << r2
        if r2
          i4 = index
          if has_terminal?('%>', false, index)
            r5 = instantiate_node(SyntaxNode,input, index...(index + 2))
            @index += 2
          else
            terminal_parse_failure('%>')
            r5 = nil
          end
          if r5
            r4 = nil
          else
            @index = i4
            r4 = instantiate_node(SyntaxNode,input, index...index)
          end
          s1 << r4
          if r4
            if index < input_length
              r6 = instantiate_node(SyntaxNode,input, index...(index + 1))
              @index += 1
            else
              terminal_parse_failure("any character")
              r6 = nil
            end
            s1 << r6
          end
        end
        if s1.last
          r1 = instantiate_node(SyntaxNode,input, i1...index, s1)
          r1.extend(StaticContent0)
        else
          @index = i1
          r1 = nil
        end
        if r1
          s0 << r1
        else
          break
        end
      end
      if s0.empty?
        @index = i0
        r0 = nil
      else
        r0 = instantiate_node(SyntaxNode,input, i0...index, s0)
        r0.extend(StaticContent1)
      end

      node_cache[:static_content][start_index] = r0

      r0
    end

    module ExecuteContent0
      def left_delimeter
        elements[0]
      end

      def tag_content
        elements[1]
      end

      def right_delimeter
        elements[2]
      end
    end

    module ExecuteContent1
      def compile
        tag_content.text_value
      end
    end

    def _nt_execute_content
      start_index = index
      if node_cache[:execute_content].has_key?(index)
        cached = node_cache[:execute_content][index]
        if cached
          cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
          @index = cached.interval.end
        end
        return cached
      end

      i0, s0 = index, []
      r1 = _nt_left_delimeter
      s0 << r1
      if r1
        r2 = _nt_tag_content
        s0 << r2
        if r2
          r3 = _nt_right_delimeter
          s0 << r3
        end
      end
      if s0.last
        r0 = instantiate_node(SyntaxNode,input, i0...index, s0)
        r0.extend(ExecuteContent0)
        r0.extend(ExecuteContent1)
      else
        @index = i0
        r0 = nil
      end

      node_cache[:execute_content][start_index] = r0

      r0
    end

    module OutputContent0
      def equal_delimeter
        elements[0]
      end

      def tag_content
        elements[1]
      end

      def right_delimeter
        elements[2]
      end
    end

    module OutputContent1
      def compile
        "p.push(#{tag_content.text_value.strip});"
      end
    end

    def _nt_output_content
      start_index = index
      if node_cache[:output_content].has_key?(index)
        cached = node_cache[:output_content][index]
        if cached
          cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
          @index = cached.interval.end
        end
        return cached
      end

      i0, s0 = index, []
      r1 = _nt_equal_delimeter
      s0 << r1
      if r1
        r2 = _nt_tag_content
        s0 << r2
        if r2
          r3 = _nt_right_delimeter
          s0 << r3
        end
      end
      if s0.last
        r0 = instantiate_node(SyntaxNode,input, i0...index, s0)
        r0.extend(OutputContent0)
        r0.extend(OutputContent1)
      else
        @index = i0
        r0 = nil
      end

      node_cache[:output_content][start_index] = r0

      r0
    end

    module Comment0
      def comment_delimeter
        elements[0]
      end

      def tag_content
        elements[1]
      end

      def right_delimeter
        elements[2]
      end
    end

    module Comment1
      def compile
        nil
      end
    end

    def _nt_comment
      start_index = index
      if node_cache[:comment].has_key?(index)
        cached = node_cache[:comment][index]
        if cached
          cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
          @index = cached.interval.end
        end
        return cached
      end

      i0, s0 = index, []
      r1 = _nt_comment_delimeter
      s0 << r1
      if r1
        r2 = _nt_tag_content
        s0 << r2
        if r2
          r3 = _nt_right_delimeter
          s0 << r3
        end
      end
      if s0.last
        r0 = instantiate_node(SyntaxNode,input, i0...index, s0)
        r0.extend(Comment0)
        r0.extend(Comment1)
      else
        @index = i0
        r0 = nil
      end

      node_cache[:comment][start_index] = r0

      r0
    end

    module TagContent0
    end

    def _nt_tag_content
      start_index = index
      if node_cache[:tag_content].has_key?(index)
        cached = node_cache[:tag_content][index]
        if cached
          cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
          @index = cached.interval.end
        end
        return cached
      end

      s0, i0 = [], index
      loop do
        i1, s1 = index, []
        i2 = index
        if has_terminal?('%>', false, index)
          r3 = instantiate_node(SyntaxNode,input, index...(index + 2))
          @index += 2
        else
          terminal_parse_failure('%>')
          r3 = nil
        end
        if r3
          r2 = nil
        else
          @index = i2
          r2 = instantiate_node(SyntaxNode,input, index...index)
        end
        s1 << r2
        if r2
          if index < input_length
            r4 = instantiate_node(SyntaxNode,input, index...(index + 1))
            @index += 1
          else
            terminal_parse_failure("any character")
            r4 = nil
          end
          s1 << r4
        end
        if s1.last
          r1 = instantiate_node(SyntaxNode,input, i1...index, s1)
          r1.extend(TagContent0)
        else
          @index = i1
          r1 = nil
        end
        if r1
          s0 << r1
        else
          break
        end
      end
      r0 = instantiate_node(SyntaxNode,input, i0...index, s0)

      node_cache[:tag_content][start_index] = r0

      r0
    end

    def _nt_equal_delimeter
      start_index = index
      if node_cache[:equal_delimeter].has_key?(index)
        cached = node_cache[:equal_delimeter][index]
        if cached
          cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
          @index = cached.interval.end
        end
        return cached
      end

      if has_terminal?('<%=', false, index)
        r0 = instantiate_node(SyntaxNode,input, index...(index + 3))
        @index += 3
      else
        terminal_parse_failure('<%=')
        r0 = nil
      end

      node_cache[:equal_delimeter][start_index] = r0

      r0
    end

    def _nt_comment_delimeter
      start_index = index
      if node_cache[:comment_delimeter].has_key?(index)
        cached = node_cache[:comment_delimeter][index]
        if cached
          cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
          @index = cached.interval.end
        end
        return cached
      end

      if has_terminal?('<%#', false, index)
        r0 = instantiate_node(SyntaxNode,input, index...(index + 3))
        @index += 3
      else
        terminal_parse_failure('<%#')
        r0 = nil
      end

      node_cache[:comment_delimeter][start_index] = r0

      r0
    end

    def _nt_left_delimeter
      start_index = index
      if node_cache[:left_delimeter].has_key?(index)
        cached = node_cache[:left_delimeter][index]
        if cached
          cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
          @index = cached.interval.end
        end
        return cached
      end

      if has_terminal?('<%', false, index)
        r0 = instantiate_node(SyntaxNode,input, index...(index + 2))
        @index += 2
      else
        terminal_parse_failure('<%')
        r0 = nil
      end

      node_cache[:left_delimeter][start_index] = r0

      r0
    end

    def _nt_right_delimeter
      start_index = index
      if node_cache[:right_delimeter].has_key?(index)
        cached = node_cache[:right_delimeter][index]
        if cached
          cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
          @index = cached.interval.end
        end
        return cached
      end

      if has_terminal?('%>', false, index)
        r0 = instantiate_node(SyntaxNode,input, index...(index + 2))
        @index += 2
      else
        terminal_parse_failure('%>')
        r0 = nil
      end

      node_cache[:right_delimeter][start_index] = r0

      r0
    end

  end

  class GrammarParser < Treetop::Runtime::CompiledParser
    include Grammar
  end

end
